### ISSUE TITLE
关于BTSerialComm中的同步

### ISSUE THREAD

**Issue by xft** [hzjerry/BluetoothSppPro#1]
我手上有个蓝牙设备，据说支持SPP。找到了这个应用。能用，还不错。浏览了下代码，暂时发现有几个问题（主要时BTSerialComm类）：
1. isConnect() 未做同步。在UI线程和其他多个线程中有调用。
2. 还有miBufDataSite这个变量也未同步。
3. mbReceiveBufs虽然表面上使用doLock() 和 doUnlock() 操作，但这两个函数并不是原子操作，在函数执行中可能被其他线程中断。
以上只是初步浏览代码后的个人见解。

**Comment by hzjerry** [comment]
非常感谢你的建议，doLock() 和 doUnlock() 的确存在你说的问题，现已修正了这个问题，这会导致miBufDataSite无法同步，这个问题比较严重会存在接收缓存丢失数据的情况。

isConnect() 这个由于并不是高频的函数，因此未作同步处理。只是用于减少掉线等待的时间。
