### ISSUE TITLE
BLE Bug

### ISSUE THREAD

**Issue by hearsilent** [hzjerry/BluetoothSppPro#3]
可以搜尋到BLE設備
但無法連接成功

**Comment by hzjerry** [comment]
你好，这个不是bug，专门设计成这样的。ble暂时还无法连接，但是能够搜索到。因为ble有专门的spp串行协议，所以没有开发连接蓝牙4.0的功能。

**Comment by hearsilent** [comment]
那如果要用這程式修改的話
該如何修改呢 ?
還是只能用Gatt處理 ?

**Comment by hzjerry** [comment]
是的，2.0与4.0完全是两个处理体系，所以我这个工具是完全不适用的，你需要用gatt处理，只有扫描部分可供你参考。
